name: Build Smart Hook

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile with Dobby
        run: |
          # نستخدم *.mm لجمع الملفات
          # -L. تعني ابحث عن المكتبات في المجلد الحالي
          # -ldobby تعني اربط ملف libdobby.a
          
          xcrun --sdk iphoneos clang -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -framework Foundation -framework UIKit \
          -O2 -fobjc-arc \
          -lc++ \
          -L. -ldobby \
          -Wno-error \
          -o Sovereign.dylib *.mm

      - uses: actions/upload-artifact@v4
        with:
          name: Sovereign_Dylib
          path: Sovereign.dylib
