name: Build Tool

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile
        run: |
          xcrun --sdk iphoneos clang -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -framework Foundation -framework UIKit \
          -O2 -fobjc-arc \
          -lc++ \
          -Wno-error \
          -o Sovereign.dylib Sovereign.mm

      - uses: actions/upload-artifact@v4
        with:
          name: Sovereign_Tool
          path: Sovereign.dylib
